In [1]:
import pandas as pd

In [3]:
#importar dados

dados_latlong = pd.read_csv('C:/Users/tumen/OneDrive/Felipe/3-Artigos/centro_gravidade/data/latlong.csv',sep = ';')
dados_populacao = pd.read_excel("C:/Users/tumen/OneDrive/Felipe/3-Artigos/centro_gravidade/data/POP2021_20221212.xls", header = 1, sheet_name="Municípios")

In [4]:
dados_populacao.head()
len(dados_populacao)

5604

In [5]:
############################
### TRATAMENTO DAS BASES ###
############################

# Eliminar linhas finais (Notas explicativas)
dados_populacao.dropna(subset = ['COD. MUNIC'], inplace=True)

#Criar coluna CodIBGE
dados_populacao['CodIBGE'] = 100000*dados_populacao['COD. UF'] + dados_populacao['COD. MUNIC']

# Separar apenas dados das cidades
dados_latlong = dados_latlong[dados_latlong['Categoria']=='CIDADE']

# Retirar as notas explicativas da coluna 'POPULAÇÃO ESTIMADA'
dados_populacao['POPULAÇÃO ESTIMADA'] = [int(str(dados_populacao['POPULAÇÃO ESTIMADA'][i]).split('(')[0].replace('.','')) for i in range(len(dados_populacao))]

In [6]:
len(dados_latlong)

5565

In [7]:
# Agrupar dados de latitude e longitude na base populacional

dados_populacao = dados_populacao.merge(dados_latlong[['CodIBGE', 'Name', 'Longitude', 'Latitude']], on = "CodIBGE", how = "left")

In [8]:
## Testar os nomes das duas bases (Resultado OK!)

dados_populacao['teste'] = [dados_populacao['NOME DO MUNICÍPIO'][i].upper()== dados_populacao['Name'][i] for i in range(len(dados_populacao))]
del dados_populacao['teste']

In [9]:
## Dados faltantes
dados_populacao[dados_populacao['Longitude'].isna()]

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,POPULAÇÃO ESTIMADA,CodIBGE,Name,Longitude,Latitude
224,PA,15.0,4752.0,Mojuí dos Campos,16282,1504752.0,NaN,NaN,NaN
4503,SC,42.0,12650.0,Pescaria Brava,10225,4212650.0,NaN,NaN,NaN
4605,SC,42.0,20000.0,Balneário Rincão,13129,4220000.0,NaN,NaN,NaN
4923,RS,43.0,14548.0,Pinto Bandeira,3068,4314548.0,NaN,NaN,NaN
5160,MS,50.0,6275.0,Paraíso das Águas,5751,5006275.0,NaN,NaN,NaN

In [10]:
##################################################
# Incluir dados faltantes (27/06/2023)
##################################################

# Mojui dos campos (https://www.cidade-brasil.com.br/municipio-mojui-dos-campos.html)
#Latitude: -2.68472
#Longitude: -54.6431
dados_populacao.loc[dados_populacao['NOME DO MUNICÍPIO']=='Mojuí dos Campos', 'Latitude'] = -2.68472
dados_populacao.loc[dados_populacao['NOME DO MUNICÍPIO']=='Mojuí dos Campos', 'Longitude'] = -54.6431

# Pescaria Brava (https://www.cidade-brasil.com.br/municipio-pescaria-brava.html)
#Latitude: -28.4247
#Longitude: -48.8956
dados_populacao.loc[dados_populacao['NOME DO MUNICÍPIO']=='Pescaria Brava', 'Latitude'] = -28.4247
dados_populacao.loc[dados_populacao['NOME DO MUNICÍPIO']=='Pescaria Brava', 'Longitude'] = -48.8956


#Balneário Rincão (https://www.cidade-brasil.com.br/municipio-balneario-rincao.html)
#Latitude: -28.8344
#Longitude: -49.2361
dados_populacao.loc[dados_populacao['NOME DO MUNICÍPIO']=='Balneário Rincão', 'Latitude'] = -28.8344
dados_populacao.loc[dados_populacao['NOME DO MUNICÍPIO']=='Balneário Rincão', 'Longitude'] = -49.2361


#Pinto Bandeira (https://www.cidade-brasil.com.br/municipio-pinto-bandeira.html)
#Latitude: -29.0978
#Longitude: -51.4503
dados_populacao.loc[dados_populacao['NOME DO MUNICÍPIO']=='Pinto Bandeira', 'Latitude'] = -29.0978
dados_populacao.loc[dados_populacao['NOME DO MUNICÍPIO']=='Pinto Bandeira', 'Longitude'] = -51.4503


#Paraíso das Águas (https://www.cidade-brasil.com.br/municipio-paraiso-das-aguas.html)
#Latitude: -19.0257
#Longitude: -53.0102
dados_populacao.loc[dados_populacao['NOME DO MUNICÍPIO']=='Paraíso das Águas', 'Latitude'] = -19.0257
dados_populacao.loc[dados_populacao['NOME DO MUNICÍPIO']=='Paraíso das Águas', 'Longitude'] = -53.0102

In [11]:
## Calcular o centro de gravidade do Brasil
populacao_total = sum(dados_populacao['POPULAÇÃO ESTIMADA'])

print(sum(dados_populacao['POPULAÇÃO ESTIMADA']*dados_populacao['Latitude'])/populacao_total)
print(sum(dados_populacao['POPULAÇÃO ESTIMADA']*dados_populacao['Longitude'])/populacao_total)

-16.990485398957283
-45.8020766490012

In [12]:
#Centros de Gravidade dos estados

resultados_estados = pd.DataFrame()
for uf in dados_populacao['UF'].unique():
    dados_estado = dados_populacao[dados_populacao['UF']==uf]
    populacao_total = sum(dados_estado['POPULAÇÃO ESTIMADA'])
    lat = sum(dados_estado['POPULAÇÃO ESTIMADA']*dados_estado['Latitude'])/populacao_total
    long = sum(dados_estado['POPULAÇÃO ESTIMADA']*dados_estado['Longitude'])/populacao_total
    linha = pd.DataFrame({"UF": uf,"Pop": populacao_total, "Latitude": lat, "Longitude": long}, index = [0])
    resultados_estados = pd.concat([resultados_estados, linha], axis = 0,  ignore_index = True)
    
resultados_estados

    UF       Pop   Latitude  Longitude
0   RO   1815278 -10.364817 -62.761797
1   AC    906876  -9.458303 -69.086400
2   AM   4269995  -3.515338 -61.254854
3   RR    652713   2.716409 -60.656835
4   PA   8777124  -2.678995 -49.568833
5   AP    877613   0.226443 -51.240158
6   TO   1607363  -9.195754 -48.286686
7   MA   7153262  -3.924591 -44.766767
8   PI   3289290  -5.797436 -42.458213
9   CE   9240580  -4.489041 -39.150419
10  RN   3560903  -5.822297 -36.067813
11  PB   4059905  -7.086531 -36.008060
12  PE   9674793  -8.212174 -36.066453
13  AL   3365351  -9.600307 -36.244918
14  SE   2338474 -10.786257 -37.272293
15  BA  14985284 -12.893253 -39.824656
16  MG  21411923 -19.668862 -44.400638
17  ES   4108508 -20.051447 -40.514021
18  RJ  17463349 -22.701573 -43.104575
19  SP  46649132 -23.002237 -47.227040
20  PR  11597484 -24.727440 -51.031118
21  SC   7338473 -27.216460 -49.688739
22  RS  11466630 -29.638060 -52.109806
23  MS   2839188 -21.002681 -54.599550
24  MT   3567234 -14.187370 -55.851911
25  GO   7206589 -16.491955 -49.181056
26  DF   3094325 -15.794087 -47.887905

In [13]:
# Centros gravitacionais das regiões

regioes = {'Norte': ['AM', 'PA', 'AC', 'RR', 'RO', 'AP', 'TO'],
          'Nordeste': ['MA', 'PI', 'CE', 'RN', 'PB', 'PE', 'AL', 'SE', 'BA'],
          'Centro Oeste': ['MS', 'MT', 'DF', 'GO'],
          'Sudeste': ['SP', 'RJ', 'MG', 'ES'],
          'Sul': ['RS', 'SC', 'PR']}

resultados_regioes = pd.DataFrame()

for regiao, lista in regioes.items():
    dados_regiao = dados_populacao[dados_populacao['UF'].isin(lista)]
    populacao_total = sum(dados_regiao['POPULAÇÃO ESTIMADA'])

    lat = sum(dados_regiao['POPULAÇÃO ESTIMADA']*dados_regiao['Latitude'])/populacao_total
    long = sum(dados_regiao['POPULAÇÃO ESTIMADA']*dados_regiao['Longitude'])/populacao_total
    linha = pd.DataFrame({"Região": regiao,"Pop": populacao_total, "Latitude": lat, "Longitude": long}, index = [0])
    resultados_regioes = pd.concat([resultados_regioes, linha], axis = 0,  ignore_index = True)
    
resultados_regioes

         Região       Pop   Latitude  Longitude
0         Norte  18906962  -4.163864 -54.762229
1      Nordeste  57667842  -8.120984 -39.036280
2  Centro Oeste  16707336 -16.637184 -51.286670
3       Sudeste  89632912 -22.012110 -45.440963
4           Sul  30402587 -27.180319 -51.113937

In [14]:
populacao_total = sum(resultados_estados['Pop'])

print(sum(resultados_estados['Pop']*resultados_estados['Latitude'])/populacao_total)
print(sum(resultados_estados['Pop']*resultados_estados['Longitude'])/populacao_total)

-16.990485398957254
-45.80207664900131